### ISSUE TITLE
error when npm install it 

### ISSUE THREAD

**Issue by shen-hui** [davidroyer/vue2-editor#116]
alert errors when installing, it can be used
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/fochier/Desktop/vue_upload-master/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/fochier/Desktop/vue_upload-master/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/fochier/Desktop/vue_upload-master/node_modules/quill-image-resize-module/node_modules/fsevents
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/fochier/Desktop/vue_upload-master/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/fochier/Desktop/vue_upload-master/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/fochier/Desktop/vue_upload-master/node_modules/quill-image-resize-module/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:957:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
node-pre-gyp ERR! System Darwin 17.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/fochier/Desktop/vue_upload-master/node_modules/quill-image-resize-module/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/fochier/Desktop/vue_upload-master/node_modules/quill-image-resize-module/node_modules/fsevents
node-pre-gyp ERR! node -v v10.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok

**Comment by zhangwei900808** [comment]
this is my error when I run install vue2-editor
```
☁  xfind-Bside [master] ⚡ sudo npm i vue2-editor
Password:
npm WARN deprecated babel-preset-es2015@6.24.0: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated is-my-json-valid@2.16.0: catastrophic backtracking in regexes could potentially lead to REDOS attack, upgrade to 2.17.2 as soon as possible
npm ERR! Unexpected end of JSON input while parsing near '...rver":"^1.16.1"},"dir'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangwei/.npm/_logs/2018-06-15T05_58_00_039Z-debug.log
```

**Comment by lhovee** [comment]
<img width="1139" alt="screen shot 2018-07-17 at 11 00 08 am" src="https://user-images.githubusercontent.com/18316780/42830411-f448506c-89b0-11e8-8b13-5016f148ef02.png">

several scary NPM audit warnings after `npm install --save vue2-editor`.

**Comment by tuannguyenminh2086** [comment]
me too. any solutions?

**Comment by davidroyer** [comment]
This issue is stale because it has been open for 60 days with no activity.

**Comment by davidroyer** [comment]
This issue was closed because it has been inactive for 7 days since being marked as stale.
