### ISSUE TITLE
why 'e.isBuffer is not a function'?

### ISSUE THREAD

**Issue by qq490507385** [davidroyer/vue2-editor#118]
The vue2-editor is good in a development environment, but bad in a production environment.Why is this?

The problem is 'e.isBuffer is not a function' at  vue2-editor.js:1.

**Comment by cooltowi** [comment]
It's problem with UglifyJS. I had the same error Today - I just fixed it. Here is an explanation: 

1. You need to install UglifyJsPlugin:
`npm i -D uglifyjs-webpack-plugin`

2. Import it:
`var UglifyJsPlugin = require('uglifyjs-webpack-plugin');`

3. In webpack.prod.conf.js replace:
```
new UglifyJsPlugin({
    compress: {
        warnings: false
    },
   sourceMap: true
})
```
with
```
new UglifyJsPlugin({
      uglifyOptions: {
        compress: {
          warnings: false
        }
      },
      sourceMap: true
    }),
```

And that's all ;)

**Comment by victorpinheiro** [comment]
When trying this solution, I had this building error:

painel@1.0.0 build /home/project
node build/build.js

⠋ building for production.../home/project/node_modules/uglifyjs-webpack-plugin/dist/index.js:321
compiler.hooks.compilation.tap(plugin, compilation => {
^

TypeError: Cannot read property 'compilation' of undefined
at UglifyJsPlugin.apply (/home/project/node_modules/uglifyjs-webpack-plugin/dist/index.js:321:20)
at Compiler.apply (/home/project/node_modules/tapable/lib/Tapable.js:375:16)
at webpack (/home/project/node_modules/webpack/lib/webpack.js:33:19)
at err (/home/project/build/build.js:20:3)
at next (/home/project/node_modules/rimraf/rimraf.js:75:7)
at CB (/home/project/node_modules/rimraf/rimraf.js:111:9)
at FSReqWrap.oncomplete (fs.js:139:20)

Can anyone please help me?

**Comment by senzonafsal** [comment]
any solution to this compiler.hooks.compilation.tap(plugin, compilation .. TypeError: Cannot read property 'compilation' of undefined .. ?

**Comment by pablocuesta92** [comment]
@victorpinheiro uglifyjs-webpack-plugin version 2 requires webpack 4. See:

[https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases)

If you're using webpack 3, try installing uglifyjs-webpack-plugin@1.3. Just replace step 1 by @cooltowi with ` npm i -D uglifyjs-webpack-plugin@1.3`

**Comment by victorpinheiro** [comment]
Sure @pablocuesta92, few weeks ago I figured this out. It indeed worked for me. Thanks for the reply!
