### ISSUE TITLE
Editor not showing when build production in Laravel+vuejs

### ISSUE THREAD

**Issue by oklnk** [davidroyer/vue2-editor#137]
I am using Laravel 5.5 and Vuejs2.5, using `yarn add vue2-editor` installed `"vue2-editor": "^2.6.6"`

Using `yarn run dev`, the editor works fine, but the editor not showing when using `yarn run prod`, click the editor area will cause a javascript error says ".TypeError: e.isBuffer is not a function"

**Comment by victorpinheiro** [comment]
Same issue here. Tryed [this solution](https://github.com/davidroyer/vue2-editor/issues/104#issuecomment-396413200) but didn't work. Caused this issue when building: 

> painel@1.0.0 build /home/project
> node build/build.js

⠋ building for production.../home/project/node_modules/uglifyjs-webpack-plugin/dist/index.js:321
    compiler.hooks.compilation.tap(plugin, compilation => {
                   ^

TypeError: Cannot read property 'compilation' of undefined
    at UglifyJsPlugin.apply (/home/project/node_modules/uglifyjs-webpack-plugin/dist/index.js:321:20)
    at Compiler.apply (/home/project/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/home/project/node_modules/webpack/lib/webpack.js:33:19)
    at err (/home/project/build/build.js:20:3)
    at next (/home/project/node_modules/rimraf/rimraf.js:75:7)
    at CB (/home/project/node_modules/rimraf/rimraf.js:111:9)
    at FSReqWrap.oncomplete (fs.js:139:20)

Can anyone please help me?

**Comment by yefeng2016** [comment]
@victorpinheiro  I find the Issue, https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/360
