### ISSUE TITLE
Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 4294967295 is invalid.

### ISSUE THREAD

**Issue by ghost** [davidroyer/vue2-editor#392]
```
quill.js:3192 Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 4294967295 is invalid.
    at Selection.setNativeRange (http://localhost:9527/app.js:281458:17)
    at Selection.setRange (http://localhost:9527/app.js:281482:29)
    at Selection.focus (http://localhost:9527/app.js:281195:12)
    at Quill.focus (http://localhost:9527/app.js:279505:22)
    at HTMLButtonElement.<anonymous> (http://localhost:9527/app.js:287724:22)
setNativeRange @ quill.js:3192
setRange @ quill.js:3216
focus @ quill.js:2929
focus @ quill.js:1239
(anonimo) @ quill.js:9458
```
happens SOMETIMES (not always) when select text (CRTL+A) and bold it or use other toolbar items
as https://github.com/quilljs/quill/issues/3080

It is always possible write other text. 
By writing new words start working again

**Comment by davidroyer** [comment]
This issue is stale because it has been open for 60 days with no activity.

**Comment by davidroyer** [comment]
This issue was closed because it has been inactive for 7 days since being marked as stale.
